CREATE TABLE ItemsTypes(
	ItemTypeID INT PRIMARY KEY IDENTITY,
	[Name] VARCHAR(20) NOT NULL
);

CREATE TABLE Items(
	ItemID INT PRIMARY KEY IDENTITY,
	[Name] VARCHAR(30) NOT NULL,
	ItemTypeID INT REFERENCES ItemsTypes(ItemTypeID)
);

CREATE TABLE Cities(
	CityID INT PRIMARY KEY IDENTITY,
	[Name] VARCHAR(20) NOT NULL
);

CREATE TABLE Customers(
	CustomerID INT PRIMARY KEY IDENTITY,
	[Name] VARCHAR(20) NOT NULL,
	Birthday DATE NOT NULL,
	CityID INT REFERENCES Cities(CityID)
);

CREATE TABLE Orders(
	OrderID INT PRIMARY KEY IDENTITY,
	CustomerID INT REFERENCES Customers(CustomerID)
);


CREATE TABLE OrderItems(
	OrderID INT REFERENCES Orders(OrderID),
	ItemID INT REFERENCES Items(ItemId)

	CONSTRAINT PK_OrderItems PRIMARY KEY(OrderId, ItemID)
);