ALTER TABLE [Users]
	DROP CONSTRAINT PK_Users;

ALTER TABLE [Users]
	ADD CONSTRAINT PK_Users
		PRIMARY KEY(Id);

ALTER TABLE [Users]
	ADD CONSTRAINT UC_Username UNIQUE (Username);

ALTER TABLE [Users]
	ADD CONSTRAINT CHK_Username CHECK (LEN(Username) >= 3);